import Navbar from "./component/layout/navbar"
import { Footer } from "./component/layout/footer"
import {Inter} from "next/font/google"
import "./globals.css";
import AuthProvider from "./context/AuthProvider";

export const metadata = {
  title: 'EdTech Next',
  description: 'Generated by Next.js',
}

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700', '900']
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProvider>
        <Navbar/>
        {children}
        <Footer/>
        </AuthProvider>
      </body>
    </html>
  )
}
